version: '2'
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
  mysql:
    image: mysql:5.6.27
    environment:
      MYSQL_ROOT_PASSWORD: example
      