version: '2'
services:
  db:
    image: mysql:5.6.27
    ports:
      - "3306:3306"
    volumes:
      - ../../:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: foo      
      MYSQL_DATABASE: codecamp
      MYSQL_USER: app
      MYSQL_PASSWORD: 123